import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {Player,type PlayerRef} from "@remotion/player";
import {DemoComposition} from "./Composition";
import initialState from "./editor-state.json";
import type {EditorState,ReviewComment} from "./types";
import {DEFAULT_LAYOUT} from "./types";
import {hideElement,mergeLayout,resetElement} from "./state";
import {sceneAtFrame} from "./editor-config";
import "./index.css";

type Dialog={mode:"element"|"canvas"|"comments"|"single";left:number;top:number;xPercent:number;yPercent:number;commentId?:string};
const api=async<T,>(path:string,body?:unknown):Promise<T>=>{const response=await fetch(path,body?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}:undefined);if(!response.ok)throw new Error(await response.text());return response.json() as Promise<T>;};

const App:React.FC=()=>{
  const player=useRef<PlayerRef>(null);const canvas=useRef<HTMLDivElement>(null);const stateRef=useRef<EditorState>(initialState);
  const [state,setState]=useState<EditorState>(initialState);const [history,setHistory]=useState<EditorState[]>([]);
  const [selected,setSelected]=useState<string>();const [label,setLabel]=useState("");const [kind,setKind]=useState("");const [dialog,setDialog]=useState<Dialog>();
  const [frame,setFrame]=useState(0);const [playing,setPlaying]=useState(false);const [comments,setComments]=useState<ReviewComment[]>([]);const [comment,setComment]=useState("");const [status,setStatus]=useState("Saved locally");
  const [dialogScale,setDialogScale]=useState(1);const [dialogShift,setDialogShift]=useState({x:0,y:0});
  const drag=useRef<{id:string;x:number;y:number;startX:number;startY:number;moved:boolean;before:EditorState}|null>(null);const dialogMove=useRef<{x:number;y:number;shiftX:number;shiftY:number}|null>(null);const dialogResize=useRef<{x:number;y:number;scale:number;corner:string}|null>(null);
  useEffect(()=>{void api<ReviewComment[]>("/api/comments").then(setComments);},[]);
  useEffect(()=>{const current=player.current;if(!current)return;const update=(event:{detail:{frame:number}})=>setFrame(event.detail.frame);const play=()=>setPlaying(true);const pause=()=>setPlaying(false);current.addEventListener("frameupdate",update);current.addEventListener("play",play);current.addEventListener("pause",pause);return()=>{current.removeEventListener("frameupdate",update);current.removeEventListener("play",play);current.removeEventListener("pause",pause);};},[]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="z"&&!event.shiftKey){event.preventDefault();undo();}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);});
  useEffect(()=>{const down=(event:Event)=>{const detail=(event as CustomEvent<{id:string;label:string;kind:string;x:number;y:number}>).detail;pointerDown(detail.id,detail.label,detail.kind,detail.x,detail.y);};const move=(event:Event)=>{const detail=(event as CustomEvent<{x:number;y:number}>).detail;pointerMove(detail.x,detail.y);};const up=()=>pointerUp();const open=(event:Event)=>openElement((event as CustomEvent<{id:string;label:string;kind:string;x:number;y:number}>).detail);window.addEventListener("simple-editor-select",down);window.addEventListener("simple-editor-move",move);window.addEventListener("simple-editor-up",up);window.addEventListener("simple-editor-open",open);return()=>{window.removeEventListener("simple-editor-select",down);window.removeEventListener("simple-editor-move",move);window.removeEventListener("simple-editor-up",up);window.removeEventListener("simple-editor-open",open);};});
  const commit=async(next:EditorState)=>{setHistory((items)=>[...items.slice(-29),stateRef.current]);stateRef.current=next;setState(next);setStatus("Saving...");await api("/api/state",next);setStatus("Saved locally");};
  const update=(patch:Parameters<typeof mergeLayout>[2])=>selected&&void commit(mergeLayout(state,selected,patch));
  const layout=selected?{...DEFAULT_LAYOUT,...state.elementLayout[selected]}:DEFAULT_LAYOUT;
  const pointerDown=(id:string,nextLabel:string,nextKind:string,x:number,y:number)=>{setSelected(id);setLabel(nextLabel);setKind(nextKind);const current={...DEFAULT_LAYOUT,...stateRef.current.elementLayout[id]};drag.current={id,x,y,startX:current.x,startY:current.y,moved:false,before:stateRef.current};};
  const pointerMove=(x:number,y:number)=>{if(!drag.current||!canvas.current)return;drag.current.moved=true;const scale=canvas.current.getBoundingClientRect().width/1080;const next=mergeLayout(stateRef.current,drag.current.id,{x:Math.round(drag.current.startX+(x-drag.current.x)/scale),y:Math.round(drag.current.startY+(y-drag.current.y)/scale)});stateRef.current=next;setState(next);};
  const pointerUp=()=>{if(!drag.current)return;const completed=drag.current;drag.current=null;if(completed.moved){setHistory((items)=>[...items.slice(-29),completed.before]);setStatus("Saving...");void api("/api/state",stateRef.current).then(()=>setStatus("Saved locally"));}};
  const placeDialog=(x:number,y:number)=>{setDialogScale(1);setDialogShift({x:0,y:0});return{left:Math.max(16,Math.min(window.innerWidth-556,x+18)),top:Math.max(16,Math.min(window.innerHeight-620,y-80))};};
  const openElement=(detail:{id:string;label:string;kind:string;x:number;y:number})=>{if(!canvas.current)return;const rect=canvas.current.getBoundingClientRect();setSelected(detail.id);setLabel(detail.label);setKind(detail.kind);setComment("");setDialog({mode:"element",...placeDialog(detail.x,detail.y),xPercent:((detail.x-rect.left)/rect.width)*100,yPercent:((detail.y-rect.top)/rect.height)*100});};
  const openDialog=(event:React.MouseEvent)=>{if(!canvas.current)return;event.preventDefault();event.stopPropagation();const rect=canvas.current.getBoundingClientRect();const node=(event.target as HTMLElement).closest<HTMLElement>("[data-editable-id]");const xPercent=Math.max(0,Math.min(100,((event.clientX-rect.left)/rect.width)*100));const yPercent=Math.max(0,Math.min(100,((event.clientY-rect.top)/rect.height)*100));if(node){openElement({id:node.dataset.editableId!,label:node.dataset.editableLabel??"Element",kind:node.dataset.editableKind??"",x:event.clientX,y:event.clientY});return;}setSelected(undefined);setLabel("Comment here");setKind("");setComment("");setDialog({mode:"canvas",...placeDialog(event.clientX,event.clientY),xPercent,yPercent});};
  const undo=()=>{const previous=history.at(-1);if(!previous)return;setHistory((items)=>items.slice(0,-1));stateRef.current=previous;setState(previous);void api("/api/state",previous);};
  const upload=async(file:File)=>{if(!selected)return;const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const result=await api<{path:string}>("/api/upload",{id:selected,name:file.name,dataUrl});await commit({...state,assetOverrides:{...state.assetOverrides,[selected]:result.path}});};
  const addComment=async()=>{if(!comment.trim()||!dialog)return;const scene=sceneAtFrame(frame);const item:ReviewComment={id:crypto.randomUUID(),frame,timeSeconds:frame/30,xPercent:Number(dialog.xPercent.toFixed(1)),yPercent:Number(dialog.yPercent.toFixed(1)),text:comment.trim(),...(selected?{elementId:selected,elementLabel:label}:{}),...(scene?{sceneId:scene.id,sceneLabel:scene.label}:{})};setComments(await api<ReviewComment[]>("/api/comments",{action:"add",comment:item}));setComment("");setDialog(undefined);};
  const removeComment=async(id:string)=>setComments(await api<ReviewComment[]>("/api/comments",{action:"delete",id}));
  const changeComment=async(item:ReviewComment)=>setComments(await api<ReviewComment[]>("/api/comments",{action:"update",comment:item}));
  const copyComments=async()=>{const text=comments.map((item,index)=>{const scene=item.sceneLabel??sceneAtFrame(item.frame)?.label??"Scene unavailable";const element=item.elementLabel?` | Element: ${item.elementLabel}${item.elementId?` | ID: ${item.elementId}`:""}`:"";return `${index+1}. ${formatTime(item.timeSeconds??item.frame/30)} | Frame ${item.frame} | Scene: ${scene}${element} | x: ${item.xPercent}%, y: ${item.yPercent}%\n${item.text}`;}).join("\n\n");await navigator.clipboard.writeText(text);};
  return <main style={{height:"100vh",display:"grid",gridTemplateRows:"64px minmax(0,1fr) 58px",background:"#101116",color:"#f7f7fa",fontFamily:"-apple-system,BlinkMacSystemFont,Arial,sans-serif"}} onPointerDown={(event)=>{if(dialog&&(event.target as HTMLElement).closest("[data-editor-dialog]")==null)setDialog(undefined);}}>
    <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 24px",borderBottom:"1px solid #30323b"}}><div><strong>Simple ChatGPT + Claude Video Editor</strong><span style={{marginLeft:12,color:"#9699a8"}}>Unofficial community project</span></div><div style={{display:"flex",alignItems:"center",gap:12}}><span style={{color:"#9699a8"}}>Double-click anywhere to comment.</span><span>{status}</span><button style={button} onClick={(event)=>{event.stopPropagation();setDialog({mode:"comments",left:Math.max(16,window.innerWidth-556),top:18,xPercent:50,yPercent:50});}}>Comments ({comments.length})</button></div></header>
    <section style={{minHeight:0,display:"grid",placeItems:"center",padding:"18px 24px 8px"}}>
      <div ref={canvas} data-editor-canvas onDoubleClickCapture={openDialog} style={{height:"100%",maxWidth:"100%",aspectRatio:"9/16",position:"relative",touchAction:"none",boxShadow:"0 20px 70px #0008"}}>
        <Player ref={player} component={DemoComposition} durationInFrames={240} fps={30} compositionWidth={1080} compositionHeight={1920} inputProps={{editorState:state,editMode:true}} controls={false} clickToPlay={false} acknowledgeRemotionLicense style={{width:"100%",height:"100%"}}/>
        <div data-review-pins style={{position:"absolute",inset:0,zIndex:1200,pointerEvents:"none"}}>{comments.map((item,index)=>Math.floor(item.frame/30)===Math.floor(frame/30)?<button key={item.id} aria-label={`Open comment ${index+1}`} title={item.text} onClick={(event)=>{event.stopPropagation();setDialog({mode:"single",...placeDialog(event.clientX,event.clientY),xPercent:item.xPercent,yPercent:item.yPercent,commentId:item.id});}} style={{position:"absolute",left:`${item.xPercent}%`,top:`${item.yPercent}%`,translate:"-50% -50%",pointerEvents:"auto",display:"grid",placeItems:"center",width:42,height:42,border:"3px solid white",borderRadius:999,background:"#0a84ff",boxShadow:"0 5px 16px #0007",color:"white",font:"800 18px -apple-system,BlinkMacSystemFont,sans-serif",cursor:"pointer"}}>{index+1}</button>:null)}</div>
      </div>
    </section>
    <footer style={{display:"grid",gridTemplateColumns:"92px 1fr 82px",alignItems:"center",gap:16,padding:"0 24px 10px",maxWidth:820,width:"100%",boxSizing:"border-box",margin:"auto"}}><button onClick={()=>playing?player.current?.pause():player.current?.play()} style={button}>{playing?"Pause":"Play"}</button><input aria-label="Video position" type="range" min={0} max={239} value={frame} onChange={(event)=>{const next=Number(event.target.value);setFrame(next);player.current?.seekTo(next);}}/><span style={{color:"#9699a8",fontVariantNumeric:"tabular-nums"}}>{(frame/30).toFixed(1)}s</span></footer>
    {dialog?<aside data-editor-dialog style={{position:"fixed",zIndex:4000,left:dialog.left+dialogShift.x,top:dialog.top+dialogShift.y,width:"min(540px,calc(100vw - 32px))",maxHeight:`calc((100vh - 32px) / ${dialogScale})`,zoom:dialogScale,overflow:"auto",display:"grid",alignContent:"start",gap:16,padding:"22px 24px",border:"1px solid #3d4050",borderRadius:22,background:"rgba(20,20,22,.98)",boxShadow:"0 24px 80px #000a"}} onPointerDown={(event)=>event.stopPropagation()}>
      <div onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);dialogMove.current={x:event.clientX,y:event.clientY,shiftX:dialogShift.x,shiftY:dialogShift.y};}} onPointerMove={(event)=>{if(dialogMove.current)setDialogShift({x:dialogMove.current.shiftX+event.clientX-dialogMove.current.x,y:dialogMove.current.shiftY+event.clientY-dialogMove.current.y});}} onPointerUp={(event)=>{dialogMove.current=null;event.currentTarget.releasePointerCapture(event.pointerId);}} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,cursor:"grab",userSelect:"none"}}><h2 style={{margin:0,fontSize:28}}>{dialog.mode==="comments"?"Review comments":dialog.mode==="single"?`Comment ${Math.max(1,comments.findIndex((item)=>item.id===dialog.commentId)+1)}`:label}</h2><button style={button} onPointerDown={(event)=>event.stopPropagation()} onClick={()=>setDialog(undefined)}>Close</button></div>
      {dialog.mode==="element"&&selected?<><Slider label="Size" value={layout.scale} min={0.1} max={3} step={0.05} onChange={(scale)=>update({scale})}/><Slider label="Turn" value={layout.rotate} min={-180} max={180} step={1} onChange={(rotate)=>update({rotate})}/><Slider label="Opacity" value={layout.opacity} min={0} max={1} step={0.05} onChange={(opacity)=>update({opacity})}/>{kind==="text"?<label>Text<textarea value={state.textOverrides[selected]??""} placeholder="Leave blank to use the default" onChange={(event)=>setState({...state,textOverrides:{...state.textOverrides,[selected]:event.target.value}})} onBlur={()=>void api("/api/state",state)} style={field}/></label>:null}{kind==="text"||kind==="color"?<label>Color<input type="color" value={state.colorOverrides[selected]??"#5367ff"} onChange={(event)=>void commit({...state,colorOverrides:{...state.colorOverrides,[selected]:event.target.value}})} style={{width:"100%",height:44}}/></label>:null}{kind==="image"?<label style={button}>Replace image<input hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event)=>event.target.files?.[0]&&void upload(event.target.files[0])}/></label>:null}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><button style={button} onClick={()=>void commit(resetElement(state,selected))}>Reset</button><button style={button} onClick={undo} disabled={!history.length}>Undo</button></div><button style={{...button,color:"#ff8e88"}} onClick={()=>void commit(hideElement(state,selected,true))}>Remove element</button><hr style={{width:"100%",borderColor:"#30323b"}}/></>:null}
      {dialog.mode==="element"||dialog.mode==="canvas"?<><label>Comment<AutoGrowTextarea value={comment} onChange={setComment}/></label><button style={{...button,background:"#0a84ff",opacity:comment.trim()?1:.45}} disabled={!comment.trim()} onClick={()=>void addComment()}>Add comment</button></>:null}
      {dialog.mode==="comments"?<><button style={{...button,background:"#0a84ff",opacity:comments.length?1:.45}} disabled={!comments.length} onClick={()=>void copyComments()}>Copy all comments</button>{comments.length?comments.map((item)=><CommentCard key={item.id} item={item} onJump={()=>{setFrame(item.frame);player.current?.seekTo(item.frame);setDialog(undefined);}} onChange={(text)=>void changeComment({...item,text})} onDelete={()=>void removeComment(item.id)}/>):<p style={{color:"#9699a8"}}>Double-click the video to add a comment.</p>}</>:null}
      {dialog.mode==="single"&&dialog.commentId?(()=>{const item=comments.find((entry)=>entry.id===dialog.commentId);return item?<CommentCard item={item} onJump={()=>{setFrame(item.frame);player.current?.seekTo(item.frame);}} onChange={(text)=>void changeComment({...item,text})} onDelete={()=>{void removeComment(item.id);setDialog(undefined);}}/>:null;})():null}
      {(["tl","tr","bl","br"] as const).map((corner)=><div key={corner} aria-label={`Resize controls from ${corner}`} onPointerDown={(event)=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);dialogResize.current={x:event.clientX,y:event.clientY,scale:dialogScale,corner};}} onPointerMove={(event)=>{const start=dialogResize.current;if(!start||start.corner!==corner)return;const horizontal=(event.clientX-start.x)*(corner.endsWith("r")?1:-1);const vertical=(event.clientY-start.y)*(corner.startsWith("b")?1:-1);setDialogScale(Math.max(.55,Math.min(1.35,start.scale+(horizontal+vertical)/520)));}} onPointerUp={(event)=>{dialogResize.current=null;event.currentTarget.releasePointerCapture(event.pointerId);}} style={{position:"absolute",...(corner.endsWith("l")?{left:-8}:{right:-8}),...(corner.startsWith("t")?{top:-8}:{bottom:-8}),width:28,height:28,cursor:corner==="tl"||corner==="br"?"nwse-resize":"nesw-resize",borderRadius:8,background:"#0a84ff",border:"3px solid white"}}/>)}
    </aside>:null}
  </main>;
};

const field:React.CSSProperties={display:"block",width:"100%",minHeight:48,marginTop:6,padding:10,border:"1px solid #3d4050",borderRadius:10,background:"#111219",color:"white"};
const button:React.CSSProperties={display:"block",padding:"10px 12px",border:"1px solid #3d4050",borderRadius:10,background:"#292b37",color:"white",cursor:"pointer"};
const formatTime=(seconds:number)=>{const minutes=Math.floor(seconds/60);const rest=(seconds%60).toFixed(3).padStart(6,"0");return `${String(minutes).padStart(2,"0")}:${rest}`;};
const AutoGrowTextarea:React.FC<{value:string;onChange:(value:string)=>void}>=({value,onChange})=>{const ref=useRef<HTMLTextAreaElement>(null);useEffect(()=>{if(ref.current){ref.current.style.height="0px";ref.current.style.height=`${Math.min(180,Math.max(82,ref.current.scrollHeight))}px`;}},[value]);return <textarea ref={ref} value={value} onChange={(event)=>onChange(event.target.value)} placeholder="What should change?" style={{...field,resize:"vertical"}}/>;};
const CommentCard:React.FC<{item:ReviewComment;onJump:()=>void;onChange:(text:string)=>void;onDelete:()=>void}>=({item,onJump,onChange,onDelete})=>{const [text,setText]=useState(item.text);const scene=item.sceneLabel??sceneAtFrame(item.frame)?.label??"Scene unavailable";return <article style={{display:"grid",gap:9,padding:14,borderRadius:16,background:"#2c2c2e"}}><button onClick={onJump} style={{...button,textAlign:"left"}}>{formatTime(item.timeSeconds??item.frame/30)} · Frame {item.frame}<br/>{scene}{item.elementLabel?` · ${item.elementLabel}`:""}<br/>x {item.xPercent}%, y {item.yPercent}%</button><AutoGrowTextarea value={text} onChange={setText}/><div style={{display:"flex",gap:10}}><button style={button} onClick={()=>onChange(text)}>Save comment</button><button style={{...button,color:"#ff6961"}} onClick={onDelete}>Delete</button></div></article>;};
const Slider:React.FC<{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}>=({label,value,min,max,step,onChange})=><label style={{display:"grid",gridTemplateColumns:"72px 1fr 72px",gap:8,alignItems:"center"}}><span>{label}</span><input type="range" value={value} min={min} max={max} step={step} onChange={(event)=>onChange(Number(event.target.value))}/><input type="number" value={value} min={min} max={max} step={step} onChange={(event)=>onChange(Number(event.target.value))} style={{...field,margin:0,minHeight:36}}/></label>;
createRoot(document.getElementById("root")!).render(<App/>);
